// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SatrancAPI.Datas;

#nullable disable

namespace SatrancApi.Migrations
{
    [DbContext(typeof(SatrancDbContext))]
    partial class SatrancDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SatrancAPI.Entities.Models.Hamle", b =>
                {
                    b.Property<Guid>("HamleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("BaslangicX")
                        .HasColumnType("int");

                    b.Property<int>("BaslangicY")
                        .HasColumnType("int");

                    b.Property<DateTime>("HamleTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("HedefX")
                        .HasColumnType("int");

                    b.Property<int>("HedefY")
                        .HasColumnType("int");

                    b.Property<Guid>("OyunId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OyuncuId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("turu")
                        .HasColumnType("int");

                    b.HasKey("HamleId");

                    b.HasIndex("OyunId");

                    b.HasIndex("OyuncuId");

                    b.ToTable("Hamleler");
                });

            modelBuilder.Entity("SatrancAPI.Entities.Models.Oyun", b =>
                {
                    b.Property<Guid>("OyunId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("BaslangicTarihi")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan?>("BeyazKalanSure")
                        .HasColumnType("time");

                    b.Property<Guid>("BeyazOyuncuId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("BeyazSkor")
                        .HasColumnType("int");

                    b.Property<DateTime?>("BitisTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Durum")
                        .HasColumnType("int");

                    b.Property<TimeSpan?>("SiyahKalanSure")
                        .HasColumnType("time");

                    b.Property<Guid>("SiyahOyuncuId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SiyahSkor")
                        .HasColumnType("int");

                    b.HasKey("OyunId");

                    b.HasIndex("BeyazOyuncuId");

                    b.HasIndex("SiyahOyuncuId");

                    b.ToTable("Oyunlar");
                });

            modelBuilder.Entity("SatrancAPI.Entities.Models.Oyuncu", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("isim")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("renk")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Oyuncular");
                });

            modelBuilder.Entity("SatrancAPI.Entities.Models.Tas", b =>
                {
                    b.Property<Guid>("TasId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<Guid>("OyunId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OyuncuId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("X")
                        .HasColumnType("int");

                    b.Property<int>("Y")
                        .HasColumnType("int");

                    b.Property<int>("renk")
                        .HasColumnType("int");

                    b.Property<int>("turu")
                        .HasColumnType("int");

                    b.HasKey("TasId");

                    b.HasIndex("OyunId");

                    b.HasIndex("OyuncuId");

                    b.ToTable("Taslar");
                });

            modelBuilder.Entity("SatrancAPI.Entities.Models.Hamle", b =>
                {
                    b.HasOne("SatrancAPI.Entities.Models.Oyun", "Oyun")
                        .WithMany("Hamleler")
                        .HasForeignKey("OyunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SatrancAPI.Entities.Models.Oyuncu", "Oyuncu")
                        .WithMany("Hamleler")
                        .HasForeignKey("OyuncuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Oyun");

                    b.Navigation("Oyuncu");
                });

            modelBuilder.Entity("SatrancAPI.Entities.Models.Oyun", b =>
                {
                    b.HasOne("SatrancAPI.Entities.Models.Oyuncu", "BeyazOyuncu")
                        .WithMany()
                        .HasForeignKey("BeyazOyuncuId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SatrancAPI.Entities.Models.Oyuncu", "SiyahOyuncu")
                        .WithMany()
                        .HasForeignKey("SiyahOyuncuId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BeyazOyuncu");

                    b.Navigation("SiyahOyuncu");
                });

            modelBuilder.Entity("SatrancAPI.Entities.Models.Tas", b =>
                {
                    b.HasOne("SatrancAPI.Entities.Models.Oyun", "Oyun")
                        .WithMany("Taslar")
                        .HasForeignKey("OyunId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SatrancAPI.Entities.Models.Oyuncu", "Oyuncu")
                        .WithMany("Taslar")
                        .HasForeignKey("OyuncuId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Oyun");

                    b.Navigation("Oyuncu");
                });

            modelBuilder.Entity("SatrancAPI.Entities.Models.Oyun", b =>
                {
                    b.Navigation("Hamleler");

                    b.Navigation("Taslar");
                });

            modelBuilder.Entity("SatrancAPI.Entities.Models.Oyuncu", b =>
                {
                    b.Navigation("Hamleler");

                    b.Navigation("Taslar");
                });
#pragma warning restore 612, 618
        }
    }
}
